# Builder Stage

# This stage builds the Next.js application.
# It installs dependencies and creates the standalone production build.
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and pnpm-lock.yaml first
# This allows Docker to cache dependency installation
COPY package.json pnpm-lock.yaml ./

# Install pnpm and dependencies
RUN npm install -g pnpm && pnpm install --frozen-lockfile

# Copy the rest of the application files
COPY . .

# Build the Next.js app using pnpm
# Because we set output: "standalone" in next.config.ts,
# this will generate a minimal production build
RUN pnpm run build


# Production Stage

# This stage creates a smaller production image.
# It only includes the necessary built files.
FROM node:20-alpine

# Set environment to production
ENV NODE_ENV=production

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Install prisma CLI for running migrations inside the container
RUN npm install -g prisma

# Set working directory
WORKDIR /app

# Install dotenv so prisma.config.ts can load
RUN npm install dotenv

# Copy the standalone server build from the builder stage
COPY --from=builder /app/.next/standalone ./

# Copy static assets required by Next.js
COPY --from=builder /app/.next/static ./.next/static

# Copy public assets (images, icons, etc.)
COPY --from=builder /app/public ./public

# Copy Prisma schema, migrations, and config for migrate deploy
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts

# Set ownership to non-root user
RUN chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port 3000 (Next.js default port)
EXPOSE 3000

# Start the standalone server
# server.js was generated by the standalone build
CMD ["node", "server.js"]